### ISSUE TITLE
RuntimeError: The size of tensor a (256) must match the size of tensor b (254) at non-singleton dimension 1

### ISSUE THREAD

**Issue by sevaroy** [VITA-Group/ShapeMatchingGAN#18]
Hi

when I run  trainStructureTransfer.py

my style image size is 848x650

I got this error

Traceback (most recent call last):
  File "trainStructureTransfer.py", line 89, in <module>
    main()
  File "trainStructureTransfer.py", line 43, in main
    opts.Sanglejitter, opts.subimg_size, opts.subimg_size)
  File "C:\Users\Artificial Dimension\Desktop\ShapeMatchingGAN\src\utils.py", line 160, in cropping_training_batches
    input[:,0] = torch.clamp(input[:,0] + noise[:,0], -1, 1)
RuntimeError: The size of tensor a (256) must match the size of tensor b (254) at non-singleton dimension 1

OS:windows 10
env:Anaconda python 3.7

how to fix it?
thx

**Comment by williamyang1991** [comment]
Sorry I missed the notification email and saw this issue so late.
I think the problem is that your image length and width are not a multiple of 4. 
You can crop your image into 848*648, and I suppose it will work properly.

I = torch.zeros(1,3,848,650)
I2 = netSketch(I, 1.0)
I2.shape --> torch.Size([1, 3, 848, 652])
