### ISSUE TITLE
One model for one style?

### ISSUE THREAD

**Issue by caihaunqai** [VITA-Group/ShapeMatchingGAN#24]
Hello, I wonder if I want to transfer, can I transfer more than one style like fire and water  with only one model.

**Comment by williamyang1991** [comment]
I haven't tried the current version on multiple styles.
But since the model is trained on image patches, maybe you can crop both the fire image and water image into patches and use them all to train a model. But I'm not sure if it will work fine.
Or using some trick like [DNI](https://xinntao.github.io/projects/DNI) to interpolate two styles.

**Comment by caihaunqai** [comment]
> I haven't tried the current version on multiple styles.
> But since the model is trained on image patches, maybe you can crop both the fire image and water image into patches and use them all to train a model. But I'm not sure if it will work fine.
> Or using some trick like [DNI](https://xinntao.github.io/projects/DNI) to interpolate two styles.

Thank you, I will read your paper and try if it can work. if time enough

**Comment by caihaunqai** [comment]
老哥，方便加您个联系方式吗？我是这个方向的小白，想咨询您点相关的问题可以吗？  我的wechat是ccchhhqqq000，感谢

**Comment by gitTongzhen** [comment]
方便加个微信吗，我的手机号是：18016669509
